# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  LinaEngine_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  LinaEngine_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  LinaEngine_config = dist
  Sandbox_config = dist
endif

PROJECTS := LinaEngine Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

LinaEngine:
ifneq (,$(LinaEngine_config))
	@echo "==== Building LinaEngine ($(LinaEngine_config)) ===="
	@${MAKE} --no-print-directory -C LinaEngine -f Makefile config=$(LinaEngine_config)
endif

Sandbox: LinaEngine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C LinaEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LinaEngine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"