# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Github-Rep\LinaEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\InanEvin\Desktop\LatestCMakeTest\12

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\InanEvin\Desktop\LatestCMakeTest\12\CMakeFiles C:\Users\InanEvin\Desktop\LatestCMakeTest\12\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\InanEvin\Desktop\LatestCMakeTest\12\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named LinaSandbox

# Build rule for target.
LinaSandbox:
	$(MAKE) -f CMakeFiles\Makefile2 LinaSandbox
.PHONY : LinaSandbox

# fast build rule for target.
LinaSandbox/fast:
	$(MAKE) -f Sandbox\CMakeFiles\LinaSandbox.dir\build.make Sandbox/CMakeFiles/LinaSandbox.dir/build
.PHONY : LinaSandbox/fast

#=============================================================================
# Target rules for targets named LinaEngine

# Build rule for target.
LinaEngine:
	$(MAKE) -f CMakeFiles\Makefile2 LinaEngine
.PHONY : LinaEngine

# fast build rule for target.
LinaEngine/fast:
	$(MAKE) -f LinaEngine\CMakeFiles\LinaEngine.dir\build.make LinaEngine/CMakeFiles/LinaEngine.dir/build
.PHONY : LinaEngine/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw:
	$(MAKE) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f LinaEngine\vendor\glfw\src\CMakeFiles\glfw.dir\build.make LinaEngine/vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files:
	$(MAKE) -f CMakeFiles\Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) -f LinaEngine\vendor\glad\CMakeFiles\glad-generate-files.dir\build.make LinaEngine/vendor/glad/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad:
	$(MAKE) -f CMakeFiles\Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f LinaEngine\vendor\glad\CMakeFiles\glad.dir\build.make LinaEngine/vendor/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... LinaSandbox
	@echo ... LinaEngine
	@echo ... glfw
	@echo ... glad-generate-files
	@echo ... glad
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

